### ISSUE TITLE
Haddock issues

### ISSUE THREAD

**Issue by asr** [afl-eafit/2018-2-lab1#1]
@elarcanista, please replace the quotes (") by at's (@) when necessary.

**Comment by asr** [comment]
Which commit closed the issue?

Note that you can [closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/) on GitHub.

**Comment by aortega0703** [comment]
Sorry, I'll have that in mind for next time. The relevant commits are 42e3be907cf63e3991f1728f596b54203b3d8002 and 3c756091d56b81fa64c36a0ea43f0a1769550e62.
